Models/Art.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ArtSkills.Models
{
    public class Art
    {
        public string Id { get; set; }
        public string ImagePath { get; set; }
        public string Name { get; set; }        
        public string UserId { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }
        public string Description { get; set; }
        public DateTime PublishDate { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }

        public Art()
        {

        }

        public Art(string name, ApplicationUser author, string description, string pictureUrl)
        {
            this.Name = name;
            this.UserId = author.Id;
            this.ImagePath = pictureUrl;
            this.Description = description;
            this.PublishDate = DateTime.Now;
            this.Comments = new List<Comment>();
        }

        public void EditInfo(string name, string description)
        {
            this.Name = name;
            this.Description = description;
        }
    }
}

Components/UserLikeViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using ArtSkills.Models;
using ArtSkills.Data;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.Web;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Task = System.Threading.Tasks.Task;

namespace ArtSkills.Components
{
    public class UserLikeViewComponent : ViewComponent
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public UserLikeViewComponent(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public async Task<IViewComponentResult> InvokeAsync(Art art)
        {
            ApplicationUser user = await GetCurrentUserAsync();

            if (user == null)
            {
                return View("DisabledLikeButton", art);
            }
            else
            {
                if (user.Id == art.ApplicationUser.Id)
                    return View("DisabledLikeButton", art);
                else return View("LikableButton", art);
            }
        }
    }
}

Controllers/ArtController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ArtSkills.Data;
using ArtSkills.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Web;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Task = System.Threading.Tasks.Task;

namespace ArtSkills.Controllers
{
    public class ArtController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private ApplicationDbContext applicationDbContext { get; }

        public ArtController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            applicationDbContext = context;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public IActionResult Art(string artID)
        {
            Art art = applicationDbContext.Arts.Find(artID);
            return View(art);
        }

        public async Task<IActionResult> ArtsCollection()
        {
            ApplicationUser user = await GetCurrentUserAsync();
            if (user != null)
                return PartialView(user.Arts);
            else
                return RedirectToAction("Index", "Home", new { area = "" });
        }

        public async Task<IActionResult> DeleteArt(String artID)
        {
            Art art = applicationDbContext.Arts.Find(artID);
            applicationDbContext.Remove(art);
            await applicationDbContext.SaveChangesAsync();
            return RedirectToAction("Index", "UserWall");
        }

        public async Task<IActionResult> LikeArt(String artID)
        {
            Art art = applicationDbContext.Arts.Find(artID);
            ApplicationUser user = await GetCurrentUserAsync();
            var like = new Like(user, art);
            if (user.Likes.ToList().Find(x => x.Art.Id == artID) == null)
            {
                applicationDbContext.Likes.Add(like);
                art.Likes.Add(like);
                user.Likes.Add(like);
                await applicationDbContext.SaveChangesAsync();
            }
            return RedirectToAction("Art", "Art", new { artID });
        }

        public async Task<IActionResult> UnlikeArt(String artID)
        {
            Art art = applicationDbContext.Arts.Find(artID);
            ApplicationUser user = await GetCurrentUserAsync();
            if (user.Likes.ToList().Find(x => x.Art.Id == artID) != null)
            {
                applicationDbContext.Remove(user.Likes.ToList().Find(x => x.Art.Id == artID));
                await applicationDbContext.SaveChangesAsync();
            }
            return RedirectToAction("Art", "Art", new { artID });
        }

        public async Task<IActionResult> CommentArt(String artID, string text)
        {
            if (text != null)
            {
                Art art = applicationDbContext.Arts.Find(artID);
                ApplicationUser user = await GetCurrentUserAsync();
                var comment = new Comment(user, art, text);
                applicationDbContext.Comments.Add(comment);
                await applicationDbContext.SaveChangesAsync();
            }
            return RedirectToAction("Art", "Art", new { artID });
        }
    }
}

Controllers/UserWallController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ArtSkills.Data;
using ArtSkills.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Web;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Task = System.Threading.Tasks.Task;
using ArtSkills.ViewModels;


namespace ArtSkills.Controllers
{

    public class UserWallController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private ApplicationDbContext applicationDbContext { get; set; }
        IHostingEnvironment _environment;

        public UserWallController(UserManager<ApplicationUser> userManager, ApplicationDbContext context,
            IHostingEnvironment environment)
        {
            _userManager = userManager;
            applicationDbContext = context;
            _environment = environment;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public async Task<IActionResult> Followers(string Id)
        {
            ApplicationUser user = applicationDbContext.Users.ToList().Find(userr => userr.Id == Id);
            var model = new UserAndArtsViewModel {user = user};
            return View(model);
        }

        public async Task<IActionResult> FollowUser(string Id)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            ApplicationUser artist = applicationDbContext.Users.ToList().Find(userr => userr.Id == Id);
            var FollowForm = new FollowArtist(artist, user);
            applicationDbContext.FollowArtists.Add(FollowForm);
            applicationDbContext.SaveChanges();
            return RedirectToAction("Index", new { Id });
        }

        public async Task<IActionResult> UnfollowUser(string Id)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            var FollowForm = user.Following.ToList().Find(x => x.FollowerId == user.Id);
            applicationDbContext.FollowArtists.Remove(FollowForm);
            applicationDbContext.SaveChanges();
            return RedirectToAction("Index", new { Id });
        }

        public async Task<IActionResult> Index(string Id, int pageNumber = 0)
        {
            if (Id == null)
            {
                ApplicationUser user = await GetCurrentUserAsync();
                if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return PartialView("~/Views/Art/ArtsCollection.cshtml", artsForThePage(pageNumber, user.Id));
                }
                var model = new UserAndArtsViewModel { Arts = artsForThePage(pageNumber, user.Id), user = user, Id = Id };
                return View(model);
            }
            else
            {
                ApplicationUser user = applicationDbContext.Users.ToList().Find(userr => userr.Id == Id);
                if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return PartialView("~/Views/Art/ArtsCollection.cshtml", artsForThePage(pageNumber, Id));
                }
                var model = new UserAndArtsViewModel { Arts = artsForThePage(pageNumber, user.Id), user = user, Id = Id };
                return View(model);
            }
        }

        const int artsCount = 5;

        public List<Art> artsForThePage(int pageNumber, string userId)
        {
            var arts = applicationDbContext.Users.ToList().Find(x => x.Id == userId).Arts.OrderByDescending(a => a.PublishDate).Skip(pageNumber * artsCount).Take(artsCount).ToList();
            return arts;
        }

        public async Task<IActionResult> About(string Id)
        {
            ApplicationUser user = applicationDbContext.Users.ToList().Find(userr => userr.Id == Id);
            var model = new UserAndArtsViewModel { user = user };
            return View(model);
        }

        public async Task<IActionResult> UploadUserPic()
        {
            ApplicationUser user = await GetCurrentUserAsync();
            var model = new UserAndArtsViewModel { user = user };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UploadUserPic(IFormFile pictureUrl)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            string path = "/Userpics/usr" + user.Id + ".jpg";
            using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
            {
                await pictureUrl.CopyToAsync(fileStream);
            }
            user.UserPic = path;  
            await _userManager.UpdateAsync(user);
            applicationDbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddArt()
        {
            ApplicationUser user = await GetCurrentUserAsync();
            var model = new UserAndArtsViewModel { user = user };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddArt(string name, IFormFile pictureUrl, string description)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            string path = "/Arts/art" + user.Id + applicationDbContext.Arts.Count().ToString() + ".jpg";
            using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
            {
                await pictureUrl.CopyToAsync(fileStream);
            }
            var art = user.PostArt(name, description, path);
            await _userManager.UpdateAsync(user);
            //applicationDbContext.Arts.Add(art);
            applicationDbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddTaskList()
        {
            ApplicationUser user = await GetCurrentUserAsync();
            var model = new UserAndArtsViewModel { user = user };
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> AddTaskList(string name, string description)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            var taskList = new TaskList(name, user, description);
            applicationDbContext.TaskLists.Add(taskList);
            applicationDbContext.SaveChanges();
            var list = user.TaskLists.ToList().Find(x => x.Name == name && x.Description == description);
            return RedirectToAction("TaskList", "TaskList", new { taskListId = list.Id });
        }

        public async Task<IActionResult> TaskListIndex(string Id)
        {
            if (Id == null)
            {
                ApplicationUser user = await GetCurrentUserAsync();
                var model = new UserAndArtsViewModel { user = user };
                return View(model);
            }
            else
            {
                ApplicationUser user = applicationDbContext.Users.ToList().Find(userr => userr.Id == Id);
                var model = new UserAndArtsViewModel { user = user };
                return View(model);
            }
        }
    }
}

Views/Art/Art.cshtml
@using ArtSkills.Models
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model Art
@{
    ViewData["Title"] = "Art";
}

<div class="post full-width">
    <div class="container-fluid extrarounded bg-lighttt">
        <div class="row">
            <div class="col-md-2">
                @if (Model.ApplicationUser.UserPic != null)
                {
                    <img class="img-circle" style="margin:10px;" height="90" width="90" src="@Model.ApplicationUser.UserPic" />
                }
                else
                {
                    <img class="img-circle" style="margin:10px;" height="90" width="90" src="~/Resources/kittyspace.png" />
                }
                <div class="post-owner" style="margin-left: 12px;">
                    @if (@Model.ApplicationUser.artistNickname != null)
                    {
                        @Html.ActionLink(@Model.ApplicationUser.artistNickname, "Index", "UserWall", new { Id = @Model.ApplicationUser.Id })

                    }
                    else
                    {
                        @Html.ActionLink(@Model.ApplicationUser.UserName, "Index", "UserWall", new { Id = @Model.ApplicationUser.Id })
                    }
                </div>
            </div>
            <div class="col-md-8">
                <div class="text-center art-name">
                    @Html.ActionLink(@Model.Name, "Art", "Art", new { artID = @Model.Id })
                    <p>@Model.PublishDate</p>
                    <hr />
                </div>
                <img class="responsive extrarounded" src="@Model.ImagePath" />
                <div class="container-fluid bg-extralighttt text-center post-text extrarounded">
                    @Model.Description
                </div>
            </div>
            @{
                var currentUser = (await UserManager.FindByIdAsync(UserManager.GetUserId(User)));
                var verified = false;
                if (currentUser != null)
                {
                    if ((await UserManager.IsInRoleAsync(currentUser, "admin")) || (await UserManager.IsInRoleAsync(currentUser, "moderator")))
                    {
                        verified = true;
                    }
                }
            }
            @if (Model.ApplicationUser.Id == UserManager.GetUserId(User) || verified == true)
            {
                <div class="col-md-2">

                    <button postId="@Model.Id" class="delete-post-button" type="submit"
                            onclick="location.href='@Url.Action("DeleteArt", "Art", new { artID = Model.Id })'"></button>
                </div>
            }
        </div>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-9">
                <div class="post-likes">
                    @await Component.InvokeAsync("UserLike", new { art = Model })
                </div>
            </div>
            <div class="text-right">@Model.Likes.Count</div>
        </div>
        <div class="row" style=" margin: auto; width: 90%">
                <div class="container-fluid commentsArea" >
                    @{await Html.RenderPartialAsync("~/Views/Comment/CommentsCollection.cshtml", @Model.Comments.ToList());}
                </div>
        </div>
        <div class="row" style=" margin: auto; width: 90%">
                <div class="container-fluid comment-sending-area">
                    <div class="row">
                        <div class="col-md-11">
                            <textarea class="form-control comment-sending-form"
                                      id="txtrev"
                                      placeholder=@Localizer["Message"]></textarea>
                        </div>
                        <div class="col-md-1">
                            <button data-assigned-id="@Model.Id" class="add-comment-button"
                                    onclick="addComment(this);"></button>
                        </div>
                    </div>
            </div>
    </div>
        </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="~/js/signalr.min.js"></script>
<script>
     function addComment(elem) {
        var id = $(elem).data('assigned-id');
            var text = document.getElementById("txtrev").value;
        location.href = '@Url.Action("CommentArt", "Art")' + '?artID=' + id + '&text=' + text;
    };
</script>

Views/Art/ArtsCollection.cshtml
@using ArtSkills.Models
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@model List<Art>
@{
    ViewData["Title"] = "ArtsCollection";
}

    <div class="container-fluid posts-container">
        @foreach (var Art in @Model)
        {
                {await Html.RenderPartialAsync("Art.cshtml", @Art);}
                <hr />
        }
    </div>