Controllers/UserWallController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ArtSkills.Data;
using ArtSkills.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Web;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Task = System.Threading.Tasks.Task;
using ArtSkills.ViewModels;


namespace ArtSkills.Controllers
{

    public class UserWallController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private ApplicationDbContext applicationDbContext { get; set; }
        IHostingEnvironment _environment;

        public UserWallController(UserManager<ApplicationUser> userManager, ApplicationDbContext context,
            IHostingEnvironment environment)
        {
            _userManager = userManager;
            applicationDbContext = context;
            _environment = environment;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public async Task<IActionResult> Followers(string Id)
        {
            ApplicationUser user = applicationDbContext.Users.ToList().Find(userr => userr.Id == Id);
            var model = new UserAndArtsViewModel {user = user};
            return View(model);
        }

        public async Task<IActionResult> FollowUser(string Id)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            ApplicationUser artist = applicationDbContext.Users.ToList().Find(userr => userr.Id == Id);
            var FollowForm = new FollowArtist(artist, user);
            applicationDbContext.FollowArtists.Add(FollowForm);
            applicationDbContext.SaveChanges();
            return RedirectToAction("Index", new { Id });
        }

        public async Task<IActionResult> UnfollowUser(string Id)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            var FollowForm = user.Following.ToList().Find(x => x.FollowerId == user.Id);
            applicationDbContext.FollowArtists.Remove(FollowForm);
            applicationDbContext.SaveChanges();
            return RedirectToAction("Index", new { Id });
        }

        public async Task<IActionResult> Index(string Id, int pageNumber = 0)
        {
            if (Id == null)
            {
                ApplicationUser user = await GetCurrentUserAsync();
                if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return PartialView("~/Views/Art/ArtsCollection.cshtml", artsForThePage(pageNumber, user.Id));
                }
                var model = new UserAndArtsViewModel { Arts = artsForThePage(pageNumber, user.Id), user = user, Id = Id };
                return View(model);
            }
            else
            {
                ApplicationUser user = applicationDbContext.Users.ToList().Find(userr => userr.Id == Id);
                if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    return PartialView("~/Views/Art/ArtsCollection.cshtml", artsForThePage(pageNumber, Id));
                }
                var model = new UserAndArtsViewModel { Arts = artsForThePage(pageNumber, user.Id), user = user, Id = Id };
                return View(model);
            }
        }

        const int artsCount = 5;

        public List<Art> artsForThePage(int pageNumber, string userId)
        {
            var arts = applicationDbContext.Users.ToList().Find(x => x.Id == userId).Arts.OrderByDescending(a => a.PublishDate).Skip(pageNumber * artsCount).Take(artsCount).ToList();
            return arts;
        }

        public async Task<IActionResult> About(string Id)
        {
            ApplicationUser user = applicationDbContext.Users.ToList().Find(userr => userr.Id == Id);
            var model = new UserAndArtsViewModel { user = user };
            return View(model);
        }

        public async Task<IActionResult> UploadUserPic()
        {
            ApplicationUser user = await GetCurrentUserAsync();
            var model = new UserAndArtsViewModel { user = user };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UploadUserPic(IFormFile pictureUrl)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            string path = "/Userpics/usr" + user.Id + ".jpg";
            using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
            {
                await pictureUrl.CopyToAsync(fileStream);
            }
            user.UserPic = path;  
            await _userManager.UpdateAsync(user);
            applicationDbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddArt()
        {
            ApplicationUser user = await GetCurrentUserAsync();
            var model = new UserAndArtsViewModel { user = user };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddArt(string name, IFormFile pictureUrl, string description)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            string path = "/Arts/art" + user.Id + applicationDbContext.Arts.Count().ToString() + ".jpg";
            using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
            {
                await pictureUrl.CopyToAsync(fileStream);
            }
            var art = user.PostArt(name, description, path);
            await _userManager.UpdateAsync(user);
            //applicationDbContext.Arts.Add(art);
            applicationDbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddTaskList()
        {
            ApplicationUser user = await GetCurrentUserAsync();
            var model = new UserAndArtsViewModel { user = user };
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> AddTaskList(string name, string description)
        {
            ApplicationUser user = await GetCurrentUserAsync();
            var taskList = new TaskList(name, user, description);
            applicationDbContext.TaskLists.Add(taskList);
            applicationDbContext.SaveChanges();
            var list = user.TaskLists.ToList().Find(x => x.Name == name && x.Description == description);
            return RedirectToAction("TaskList", "TaskList", new { taskListId = list.Id });
        }

        public async Task<IActionResult> TaskListIndex(string Id)
        {
            if (Id == null)
            {
                ApplicationUser user = await GetCurrentUserAsync();
                var model = new UserAndArtsViewModel { user = user };
                return View(model);
            }
            else
            {
                ApplicationUser user = applicationDbContext.Users.ToList().Find(userr => userr.Id == Id);
                var model = new UserAndArtsViewModel { user = user };
                return View(model);
            }
        }
    }
}

Views/UserWall/About.cshtml
@using ArtSkills.Models
@using ArtSkills.ViewModels
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model UserAndArtsViewModel
@{
    ViewData["Title"] = "About";
    Layout = "_Layout.cshtml";
}

<div class="row">
    <div class="col-4 text-center">
        <img src="~/Resources/kittypaint.png" />
    </div>
    <div class="col-4 text-center bg-extralighttt extrarounded">
        <h3>@Localizer["Basic"]</h3>
        <hr />
        <form id="profile-form" method="post" class="">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label>@Localizer["Name"]</label>
                <input asp-for=@Model.user.Name class="form-control bg-white" disabled />
            </div>
            <div class="form-group">
                <label>@Localizer["Surname"]</label>
                <input asp-for=@Model.user.Surname class="form-control bg-white" disabled />
            </div>
            <div class="form-group">
                <label>@Localizer["BirthDate"]</label>
                <input asp-for=@Model.user.DateOfBirth class="form-control bg-white" disabled />
            </div>
        </form>
        <hr />
        <h3>@Localizer["Statistics"]</h3>
        @{
            int progress = Model.user.TaskLists.ToList().FindAll(x => x.Status == true).Count;
        }
        <hr />
        <div class="form-group">
            <label>@Localizer["Progress"]</label>
            <div progress-value="progress" progress-max="@Model.user.TaskLists.Count"></div>
        </div>
        <p>@Localizer["TaskCount"] @Model.user.TaskLists.Count</p>
        <hr />
        <div class="form-group">
            <label>@Localizer["Registration"]</label>
            <input asp-for=@Model.user.RegistrationDate class="form-control bg-white" disabled />
        </div>
        <div class="form-group" style="padding-bottom:10px;">
            <label>@Localizer["ArtCount"]</label>
            <input asp-for=@Model.user.Arts.Count class="form-control bg-white" disabled />
        </div>
    </div>
    <div class="col-4 text-center">
        <img src="~/Resources/kittypaint.png" />
    </div>
</div>

Views/UserWall/AddArt.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using ArtSkills.ViewModels
@model UserAndArtsViewModel
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = "Add art";
    Layout = "_Layout.cshtml";
}

<div class="col-4 offset-4 text-center">
    <h3>@Localizer["Title"]</h3>
    <hr />

    <form asp-action="AddArt" method="post" enctype="multipart/form-data">
        <fieldset>
            <legend>@Localizer["Name"]</legend>
            <input name="name" class="form-control bg-white" required />
        </fieldset>

        <fieldset>
            <legend>@Localizer["Load"]</legend>
            <input name="pictureUrl" type="file" class="form-control bg-image" required />
        </fieldset>
        <hr />
        <fieldset>
            <legend>@Localizer["Description"]</legend>
            <textarea name="Description" rows="5" cols="44"> </textarea>
        </fieldset>
        <hr />
        <button type="submit" class="btn btn-primary">@Localizer["Add"]</button>

    </form>
</div>

Views/UserWall/AddTaskList.cshtml
@using ArtSkills.ViewModels;
@model UserAndArtsViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = "Add tasklist";
}

<div class="col-4 offset-4 text-center">
    <h3>@Localizer["Title"]</h3>
    <hr />

    <form asp-action="AddTaskList" method="post">
        <fieldset>
            <legend>@Localizer["Name"]</legend>
            <input name="name" class="form-control bg-white" required />
        </fieldset>
        <fieldset>
            <legend>@Localizer["Description"]</legend>
            <textarea name="Description" rows="5" cols="44"> </textarea>
        </fieldset>
        <hr />
        <button type="submit" class="btn btn-primary">@Localizer["Add"]</button>

    </form>
</div>

Views/UserWall/Followers.cshtml
@using ArtSkills.Models
@using ArtSkills.ViewModels
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@model UserAndArtsViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = "Followers";
}

<div class="text-center bg-image">
    <h2>@Localizer["Followers"]</h2>
    <hr />
</div>

@if (Model.user.FollowedBy.Count != 0)
{
    <div class="followers-list">
        <div class="row">
            @foreach (var follower in Model.user.FollowedBy)
            {
                <div class="col-lg-3 col-md-4 col-sm-6 col-12">
                    <div class="follower-info full-width extrarounded">
                        <div class="follower-up-info">
                            @if (follower.Follower.UserPic == null)
                            {
                                <img src="~/Resources/kittyspace.png" />
                            }
                            else
                            {
                                <img src="@Url.Content(follower.Follower.UserPic)" />
                            }
                        </div>
                        @if (follower.Follower.artistNickname != null)
                        {
                            @Html.ActionLink(follower.Follower.artistNickname, "Index", "UserWall", new { Id = follower.Follower.Id })
                        }
                        else
                        {
                            @Html.ActionLink(follower.Follower.UserName, "Index", "UserWall", new { Id = follower.Follower.Id })
                        }
                    </div>
                </div>

            }
        </div>
    </div>
}
else
{
    <div class="text-center">
        <h4>No followers yet!</h4>
    </div>
}

Views/UserWall/Index.cshtml
@using ArtSkills.Models
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@using ArtSkills.ViewModels;
@model UserAndArtsViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "_Layout.cshtml";
}


<div data="@Model.Id" id="idGiver"></div>

@if (Model.Arts.Count != 0)
{
    <div class="posts" id="postsArea">
        @{await Html.RenderPartialAsync("~/Views/Art/ArtsCollection.cshtml", Model.Arts);}
    </div>
}
else
{
    <div class="text-center">
        <h1>@Localizer["Message"]</h1>
    </div>
}

<script>
    $(function () {
        var pageNumber = 0;
        var _inCallback = false;
        var Id = '@Model.Id';
        function getArts() {
            if (pageNumber > -1 && !_inCallback) {
                _inCallback = true;
                pageNumber++;
                $.ajax({
                    type: 'GET',
                    url: '/UserWall/Index/',
                    data: {
                        Id: Id,
                        pageNumber: pageNumber
                    },
                    success: function (data) {
                        if (data != '') {
                            $(".posts").append(data);
                        }
                        else {
                            pageNumber = -1;
                        }
                        _inCallback = false;
                    }
                });
            }
        }
        $(window).scroll(function () {
            if ($(window).scrollTop() + $(window).height() > $(document).height() - 50) {
                   getArts();
            }
        });
    })
</script>

Views/UserWall/TaskListIndex.cshtml
@using ArtSkills.Models
@using ArtSkills.ViewModels
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model UserAndArtsViewModel
@{
    ViewData["Title"] = "TaskListIndex";
    Layout = "_Layout.cshtml";
}

<div class="text-center bg-image">
    <h3>@Localizer["Title"]</h3>
    <hr />
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default bg-white">@Html.ActionLink("Completed", "Completed", "TaskList", new { Id = Model.user.Id })</button>
        <button type="button" class="btn btn-default bg-white active">@Html.ActionLink("In progress", "InProgress", "TaskList", new { Id = Model.user.Id })</button>
    </div>
    <hr />
</div>

@if (Model.user.TaskLists.Count != 0)
{
    { await Html.RenderPartialAsync("~/Views/TaskList/TaskListsCollection.cshtml", @Model.user.TaskLists.OrderByDescending(a => a.StartDate).ToList()); }
}
else
{
    <div class="text-center">
        <h1>@Localizer["Message"] </h1>
    </div>
}

Views/UserWall/UploadUserPic.cshtml
@using ArtSkills.ViewModels;
@model UserAndArtsViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = "Changing avatar.";
    Layout = "_Layout.cshtml";
}

<div class="col-4 offset-4 text-center">
    <h3>@Localizer["Title"]</h3>
    <hr />

    <form asp-action="UploadUserPic" method="post" enctype="multipart/form-data">
        <fieldset>
            <legend>@Localizer["Load"]</legend>
            <input name="pictureUrl" type="file" class="form-control bg-image" required />
        </fieldset>
        <hr />
        <button type="submit" class="btn btn-primary">@Localizer["Upload"]</button>
    </form>
</div>

Views/UserWall/_Layout.cshtml
@using ArtSkills.Models
@using ArtSkills.ViewModels;
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Rewrite.Internal.UrlActions
@inject UserManager<ApplicationUser> UserManager
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model UserAndArtsViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="text-center bg-image">
    @if (Model.user.UserPic == null)
    {
        <img src="~/Resources/kittyspace.png" style="padding: 10px;" alt="" />

    }
    else
    {
        <img src="@Model.user.UserPic" class="img-circle" height="175" width="175" />
    }
    @if (Model.user.artistNickname != null)
    {
        <h1>@Model.user.artistNickname</h1>
    }
    else
    {
        <h1>@Model.user.UserName</h1>
    }
    <p>@Model.user.About</p>
    <p>@Localizer["Followers"] @Model.user.FollowedBy.Count</p>
    @if (Model.user.Id != UserManager.GetUserId(User))
    {
        if (Model.user.FollowedBy.ToList().Find(x => x.FollowerId == UserManager.GetUserId(User)) != null)
        {
            <button id="remove-follower-button"
                    onclick="location.href='@Url.Action("UnfollowUser", "UserWall", new { Id = Model.user.Id })'"
                    class="btn btn-primary">
                @Localizer["Unfollow"]
            </button>
        }
        else
        {
            <button id="update-profile-button" data-assigned-id="@Model.user.Id"
                    onclick="follow(this);"
                    class="btn btn-primary">
                @Localizer["Follow"]
            </button>
        }
    }
    @if (Model.user.Id == UserManager.GetUserId(User))
    {
        <div class="btn-group" role="group">
            <form method="get" asp-controller="UserWall" asp-action="AddArt">
                <button id="addArt" class="btn btn-primary">@Localizer["Load"]</button>
            </form>
            <form method="get" asp-controller="UserWall" asp-action="AddTaskList">
                <button id="add_tasklist" class="btn btn-primary">@Localizer["Add"]</button>
            </form>
            <form method="get" asp-controller="UserWall" asp-action="UploadUserPic">
                <button id="uploadUserPic" class="btn btn-primary">@Localizer["ChangeAvatar"]</button>
            </form>
        </div>
        <!--if (Model.UserRole == "admin" || Model.UserRole == "moderator")-->
        if ((await UserManager.GetRolesAsync(Model.user)).Contains("admin") || (await UserManager.GetRolesAsync(Model.user)).Contains("moderator"))
        {
            <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="Index">@Localizer["Administration"]</a>
        }
    }
</div>
<hr>
<div class="text-center">
    <partial name="_UserWallNavigation" />
    <hr />
</div>
<script src="~/js/signalr.min.js"></script>
<script>
    const hubConnection = new signalR.HubConnectionBuilder()
        .withUrl("/notifications")
        .build();

        hubConnection.on('Notify', function (message) {
            alert(message);
        });

    function follow(elem) {
        var id = $(elem).data('assigned-id');
        hubConnection.invoke('Follow', id);
        location.href = '@Url.Action("FollowUser", "UserWall")' + '?Id=' + id;
    };

    hubConnection.start();
</script>

@RenderBody()

Views/UserWall/_UserWallNavigation.cshtml
@using ArtSkills.Models
@using ArtSkills.ViewModels
@model UserAndArtsViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<div class="btn-group" role="group">
    <button type="button" class="btn btn-default bg-white">@Html.ActionLink(Localizer["About"].Value, "About", "UserWall", new { Id = Model.user.Id })</button>
    <button type="button" class="btn btn-default bg-white active">@Html.ActionLink(Localizer["Arts"].Value, "Index", "UserWall", new { Id = Model.user.Id })</button>
    <button type="button" class="btn btn-default bg-white">@Html.ActionLink(Localizer["TaskLists"].Value, "TaskListIndex", "UserWall", new { Id = Model.user.Id })</button>
    <button type="button" class="btn btn-default bg-white">@Html.ActionLink(Localizer["Followers"].Value, "Followers", "UserWall", new { Id = Model.user.Id })</button>
</div>